version: '3.2'

services:

    websocket-server:
        image: node:latest
        container_name: ${COMPOSE_PROJECT_NAME}-websocket-server
        volumes:
            - ./server:/app
        working_dir: /app
        command: ["npm", "run", "dev"]
        ports:
            - "${WS_PORT}:3001"
        env_file:
            - .env
        environment:
            - HOST=0.0.0.0
            - PORT=3001

    webserver:
        image: nginx:latest
        container_name: ${COMPOSE_PROJECT_NAME}-webserver
        volumes:
            - ./client:/usr/share/nginx/html
        working_dir: /app
        ports:
            - "${CLIENT_PORT}:80"
        env_file:
            - .env
