version: '3.2'

services:

    websocket-server:
        image: node:latest
        container_name: ${COMPOSE_PROJECT_NAME}-websocket-server
        volumes:
            - .:/app
        working_dir: /app
        command: ["npm", "run", "dev"]
        ports:
            - "${CLIENT_PORT}:3001"
        env_file:
            - .env
        environment:
            - HOST=0.0.0.0
            - PORT=3001
